#!/bin/sh

set -e -x

# Kernel Source
KERNEL_SOURCE="https://github.com/ansh-m14x/kernel-oppo-a31"
KERNEL_BRANCH="Ksu"
KERNEL_DEFCONFIG="oppo6765_19581_defconfig"

# Prebuilt Clang Toolchain (AOSP)
CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-9.0.0_r3/clang-4691093.tar.gz"
GCC_x64="https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9"
GCC_x32="https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9"
GCC_BRANCH="master-kernel-build-2021"

# Setup make Command
make_fun() {
	make O=out ARCH=arm64 CC=clang HOSTCC=clang DTC=dtc \
		CLANG_TRIPLE=aarch64-linux-gnu- \
		CROSS_COMPILE=aarch64-linux-androidkernel- "$@"
}

# Work Path
WORK="${HOME}/work"
KERNEL="myKernel"
KERNEL_SRC="${WORK}/${KERNEL}"

# Prepare Directory
mkdir -p "${WORK}"
cd "${WORK}" || exit 1

# Cloning all the Necessary files
if [ ! -d clang ]; then mkdir clang && curl -Lsq "${CLANG_URL}" -o clang.tgz && tar -xzf clang.tgz -C clang; fi
[ ! -d x64 ] && git clone --depth=1 "${GCC_x64}" -b "${GCC_BRANCH}" ./x64
[ ! -d x32 ] && git clone --depth=1 "${GCC_x32}" -b "${GCC_BRANCH}" ./x32
[ ! -d "${KERNEL}" ] && git clone --depth=1 "${KERNEL_SOURCE}" -b "${KERNEL_BRANCH}" "${KERNEL}"

# Setting Toolchain Path
PATH="${WORK}/clang/bin:${WORK}/x64/bin:${WORK}/x32/bin:/bin"

# Enter Kernel root directory
cd "${KERNEL_SRC}" || exit 1

# 1. Clone KernelSU v0.9.5 into drivers/kernelsu
if [ ! -d "drivers/kernelsu" ]; then
    git clone https://github.com/tiann/KernelSU -b v0.9.5 drivers/kernelsu
fi

# 2. Start Compiling (Initial Config)
make_fun "${KERNEL_DEFCONFIG}"

# 3. Apply Config Overrides
chmod +x scripts/config

# Enable KSU and necessary filesystem support
./scripts/config --file out/.config -e KSU
./scripts/config --file out/.config -d KSU_WITH_KPROBES
./scripts/config --file out/.config -e OVERLAY_FS

# Fix "undefined reference" for Lcm_name, Ctp_name, and Charger
./scripts/config --file out/.config -e MTK_LCM
./scripts/config --file out/.config -e TOUCHSCREEN_MTK
./scripts/config --file out/.config -e MTK_BATTERY_CHARGER_ALL

# 4. Final Build
make_fun -j2"$(nproc --all)" 2>&1 | tee build.log
