name: OZIP Decrypter

on:
  workflow_dispatch:

env:
  FIRMWARE_LINK: https://assorted.downloads.oppo.com/firmware/CPH2015/CPH2015PUEX_11_OTA_0610_all_wv6l4jM4JLIV.ozip
  FIRMWARE_NAME: CPH2015PUEX_11_OTA_0610_all_wv6l4jM4JLIV.ozip
  FIRMWARE_ZIP_NAME: CPH2015
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
       - name: Checkout
         uses: actions/checkout@v4
         
       - name: Downloading Ozip Now.. 
         run: |
            sudo apt-get update
            sudo apt install aria2 python3-pip zip jq -y
            aria2c "$FIRMWARE_LINK"
             
       - name: Decrypting Ozip Now
         run: |
             pip3 install setuptools wheel docopt pycryptodome
             wget https://raw.githubusercontent.com/techyminati/oppo_ozip_decrypt/master/ozipdecrypt.py
             python3 ozipdecrypt.py "$FIRMWARE_NAME"
             zip -r "$FIRMWARE_ZIP_NAME.zip" ./out/*

       - name: Upload to GoFile (Unlimited Size)
         run: |
             # GoFile server check aur upload
             SERVER=$(curl -s https://api.gofile.io/getServer | jq -r .data.server)
             RESPONSE=$(curl -F "file=@${{ env.FIRMWARE_ZIP_NAME }}.zip" https://${SERVER}.gofile.io/uploadFile)
             DOWNLOAD_LINK=$(echo $RESPONSE | jq -r .data.downloadPage)
             echo "--------------------------------------------------"
             echo "DOWNLOAD LINK: $DOWNLOAD_LINK"
             echo "--------------------------------------------------"
