name: OZIP Decrypter

on:
  workflow_dispatch: # Isse "Run Workflow" ka button aa jayega

env:
  FIRMWARE_LINK: https://assorted.downloads.oppo.com/firmware/CPH2015/CPH2015PUEX_11_OTA_0610_all_wv6l4jM4JLIV.ozip
  FIRMWARE_NAME: CPH2015PUEX_11_OTA_0610_all_wv6l4jM4JLIV.ozip
  FIRMWARE_ZIP_NAME: CPH2015
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
       - name: Checkout
         uses: actions/checkout@v4
         
       - name: Downloading Ozip Now.. 
         run: |
            sudo apt-get update
            sudo apt install aria2 expect python3-pip -y
            aria2c "$FIRMWARE_LINK"
             
       - name: Decrypting Ozip Now
         run: |
             # Dependencies install karne ka sahi tarika
             pip3 install setuptools wheel docopt pycryptodome
             wget https://raw.githubusercontent.com/techyminati/oppo_ozip_decrypt/master/ozipdecrypt.py
             python3 ozipdecrypt.py "$FIRMWARE_NAME"
             # Out folder check karke zip banana
             zip -r "$FIRMWARE_ZIP_NAME.zip" ./out/*

       - name: Upload Decrypted Zip
         run: |
              # Pehle check kar ki file bani bhi hai ya nahi
              ls -lh "$FIRMWARE_ZIP_NAME.zip"
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\" { send \"yes\r\"; exp_continue }
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put $FIRMWARE_ZIP_NAME.zip\r\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
